 name: "Checkov SAST Scan for Terraform .tfplan files as well as source code"
 
 on:
   workflow_dispatch:
   push:
     branches:
       - '*'
     paths:
       - ./**
   pull_request:
     branches:
       - main
     types:
       - opened
       - synchronize
     paths:
       - ./**
 
 permissions:
   contents: read
   id-token: write
   actions: read
   security-events: write
 
 jobs:
   sast-checkov-scan-plan:
     uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-tfplan.yaml@x.x.x
     with:
       # Optional inputs depending on code structure
       path: 'e.g. terraform/environment/sandbox-ops-tooling'
       env_name: 'e.g. sandbox-ops-tooling'
       plan_role: '<role with permissions for generating a plan>'
     # Github secret containing the AWS Account ID.
     secrets:
       account_id: ${{ e.g secrets.<account_name>_account_id }}
