 name: Checkov SAST Scan
 
 on:
   workflow_call:

 permissions:
   contents: read
   id-token: write
   actions: read
   security-events: write

 jobs:
   checkov-scan:
     uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.4.0
